### ISSUE TITLE
RPC error during uploading contract

### ISSUE THREAD

**Issue by shreyaspg** [InterWasm/cw-template#102]
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account wasm1emfs7gk3jmtcnp2wfnapt2zp6ll6h5fk9mtdrn not found: key not found

I am running this command  `RES=$(wasmd tx wasm store ./cw_nameservice.wasm --from wallet $TXFLAG -y --output json)`, I have generated the key using the doc and can see it in my .home/wasmd directory

**Comment by ethanfrey** [comment]
You need tokens on the account you send from.

Also, you don't explain where you are connecting to.
Can you please [get on Discord](https://chat.cosmwasm.com) to ask for help?
