### ISSUE TITLE
Add Integration Package tests

### ISSUE THREAD

**Issue by entrancedjames** [InterWasm/cw-template#103]
One pattern I think would benefit new cosmwasm developers would be to have a scaffold for integration tests by creating a new package called test in the main directory. 

Having a seperate folder package for integration tests might provide more clarity toward the functionality of each unit tests in the src package. More complex testing that requires instantiation and sequences of executing and query could then be pulled out to integration tests. Thoughts?

One con is that this might be defining too much of the behavior to users (and forces them into following this pattern).

**Comment by ethanfrey** [comment]
Do you mean cosmwasm-vm style integration tests (which won't really provide much to most users)

Or showing how to use multitest?

This is an advanced behavior and I think outside of a template. But links to proper patterns would be good in the readme.

**Comment by entrancedjames** [comment]
cosmwasm-vm style integration tests, or as well as maybe multi-test but agree this is too complicated for a starter. closing this out, thank you Ethan
